### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Kabron287** [mayermakes/Sudoflash#1]
Board LILYGO_T-DISPLATY-S3, Windows 10 WSL
I did all as instructed, got no errors and the same log as in video, but when I connect
terminal to board I got the following and nothing more:

etc ptr = 0x420b0000                                                            
ESP-ROM:esp32s3-20210327                                                        
Build:Mar 27 2021                                                               
rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)                   
Saved PC:0x42069906                                                             
SPIWP:0xee                                                                      
mode:DIO, clock div:1                                                           
load:0x3fce3808,len:0x1064                                                      
load:0x403c9700,len:0x9e0                                                       
load:0x403cc700,len:0x291c                                                      
entry 0x403c98d8                                                                
etc ptr = 0x420b0000                                                            
linux ptr = 0x42120000                                                          
rootfs ptr = 0x42480000

**Comment by mayermakes** [comment]
you are looking at the wrong  port. that output is the boot log on native USB  .looking at that log it seems flashing has worked fine. If you are flashing the linked binaries the linux terminal is on the UART port. I recommend using Putty to connect to it.
115200 Baud.

**Comment by mayermakes** [comment]
direct support on discord.mayermakes.com
resolved issue. just looking at wrong port confirmed.
